# Generated by Django 3.2 on 2023-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(default=0.0005263157894736842, verbose_name='Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default=0.0005263157894736842, max_length=150, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
