# Generated by Django 4.2.2 on 2023-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivelAutorizacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
