# Generated by Django 3.2 on 2023-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20230605_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(max_length=10, verbose_name='DNI'),
        ),
    ]
