# Generated by Django 4.2.2 on 2023-06-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantDormitorios', models.PositiveIntegerField()),
                ('cantPersonas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplejoCabanias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfilcliente')),
                ('id_cabania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cabania')),
                ('id_complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.complejocabanias')),
            ],
        ),
        migrations.AddField(
            model_name='cabania',
            name='idComplejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.complejocabanias'),
        ),
        migrations.AddField(
            model_name='cabania',
            name='servicios',
            field=models.ManyToManyField(to='principal.servicio'),
        ),
    ]
