# Generated by Django 4.2.2 on 2023-06-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cabania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantDormitorios', models.PositiveIntegerField()),
                ('cantPersonas', models.PositiveIntegerField()),
                ('idComplejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.complejocabanias')),
                ('servicios', models.ManyToManyField(to='principal.servicio')),
            ],
        ),
    ]
