# Generated by Django 4.2.2 on 2023-06-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('principal', '0002_servicio_cabania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('senia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cabania')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfilcliente')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.complejocabanias')),
            ],
        ),
    ]
