# Generated by Django 4.2.2 on 2023-06-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cabana',
            new_name='id_cabania',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='complejo',
            new_name='id_complejo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago_total',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='senia',
        ),
    ]
